name = "Homiecraft"
author = "williehank"
version = "alpha10"
description = "# Homiecraft\n\nA modpack designed to be an easy intro to modded Minecraft. Centered around the excellent Create mod with  additional decoration and world gen mods keeps everyone engaged. Whether tinkering with machines, building expansive cities or exploring brand new biomes and dungeons. \n\n## Disclaimer\n\nThis mod pack is currently in **alpha**. The mod list is not fully solidified yet and mods may be added or removed between versions.\n"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "485c3b892e57cc3130c56741d98fb0fd3c59cfa398c6d22591c64da29351d1c1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
